### ISSUE TITLE
Document volumes shorthand `:z` and `:Z` suffixes used in docker.

### ISSUE THREAD

**Issue by jtagcat** [compose-spec/compose-spec#191]
Docker has

> Two suffixes :z or :Z can be added to the volume mount. These suffixes tell Docker to relabel file objects on the shared volumes. The 'z' option tells Docker that the volume content will be shared between containers. Docker will label the content with a shared content label. Shared volumes labels allow all containers to read/write content. The 'Z' option tells Docker to label the content with a private unshared label. Private volumes can only be used by the current container.

**Comment by EricHripko** [comment]
Hi @jtagcat 👋 Thank you for sharing this feedback - could you please fill out the [issue template](https://github.com/compose-spec/compose-spec/issues/new) for additional context?

**Comment by jtagcat** [comment]
Docker uses `:z` and `:Z`, but it isn't reflected in the compose spec.

I understand the spec is supposed to be upstream to docker, yet if software use a warped spec, it's useless to use the spec as a reference in writing compose files (as the end 'user').

**Comment by tymonx** [comment]
I was trying to use the [docker-compose](https://github.com/docker/compose) CLI v2 with SELinux label bind option but there is a regression compared to the CLI v1 written in Python. Because of that I have created several patches:

- documenting SELinux bind option https://github.com/compose-spec/compose-spec/pull/221
- adding support for `:z` `:Z` in Compose Go YAML parser https://github.com/compose-spec/compose-go/pull/213
- currently working on adding support for `:z` `:Z` options in the [docker-compose](https://github.com/docker/compose) CLI v2

**Comment by tymonx** [comment]
Related https://github.com/docker/compose/issues/9072

**Comment by EricHripko** [comment]
Thank you for sharing the extra context @tymonx, really appreciate it 👍
