### ISSUE TITLE
Unsupported config option for services: xxx

### ISSUE THREAD

**Issue by GF-Huang** [compose-spec/compose-spec#259]
Why got error?

![image](https://user-images.githubusercontent.com/4510984/169645061-43514be6-71ba-4e02-baee-37c27d1e2cfb.png)

![image](https://user-images.githubusercontent.com/4510984/169645088-a8b10656-0cdd-41d6-8b52-2078416c4011.png)

![image](https://user-images.githubusercontent.com/4510984/169645121-2fbd1c15-01ab-4de6-9be0-9c142b43ecf0.png)

**Comment by glours** [comment]
Hello
Can you test your Compose version with `docker-compose --version` if it's mention `v1.x.x` can you check if you compose v2 is also installed with `docker compose version`.

Then you can you past the output of `docker compose config` please?

**Comment by GF-Huang** [comment]
Oh, I found that is `1.25.0`. I think it is the reason. Thanks your tips.

**Comment by GF-Huang** [comment]
@glours By the way, how can I make `docker compose` alias to `docker-compose`? And now when I type `docker com` then `tab`, it only show me `docker commit`. There is no `docker compose` in its command list. Why?

**Comment by glours** [comment]
If you're using Docker Desktop, you just need to check the `Use Docker Compose V2` the general tab of the settings.
Otherwise, the best option is to uninstall Compose V1 and then just add an alias in your shell configuration.

For the completion work in progress, it has just been merged in Docker CLI and a PR has been opened in Compose 
https://github.com/docker/compose/pull/9462
