### ISSUE TITLE
Define "project" 

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#28]
**What is the problem you're trying to solve**
Specification make reference to "project_name" which is specific to docker-compose implementation.

**Describe the solution you'd like**
Specification should define what a "project" is, or use another noun ("application" ?)

**Comment by BigMorty** [comment]
Application seems like the obvious choice.

**Comment by masi** [comment]
I tend to use application like program. Like docker-compose projects they can be run simultaneously. As a programmer it resembles more the concept of instance of  class.

Deploy does not feel right. Just because I spin up a VM does not I deploy anything.

Note: I'm using docker-compose mainly to run VMs on my local machine to develop web applications. In this scenario I do not deploy anything and using the -p flag will not change the name of the application I'm creating.
