### ISSUE TITLE
Mechanism for override file to **remove** element

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#284]
**What is the problem you're trying to solve**
compose.yaml can be merged to override attributes, but there's no way to REMOVE an element

**Describe the solution you'd like**
Some way for user to explicitly define an key to REMOVE element in overridden compose model

An [interesting proposal](https://github.com/docker/compose/issues/3729#issuecomment-1083928255) is to rely on yaml `null` syntax:
```
services:
  app:
    ports: ~
```

Using this, whenever the base compose file might define `ports` for `app` service, the merged model with such an explicit `null` attribute will have no port set.

**Comment by milas** [comment]
For `ShellCommand` in `compose-go`, we ran into something sorta similar to this - if you wanted to clear the command set via `CMD` (or `ENTRYPOINT`) in the `Dockerfile`, it'd get lost during marshaling.

It now distinguishes between `[]` and `nil`, which is annoying in the Go code, but works. See https://github.com/compose-spec/compose-go/pull/298.

I'm mentioning because it's almost the exact opposite semantically - if the user specifies `[]`, we'll use that value, but if they provide `null` (either explicitly or implicitly by not setting the field), we ignore it.

We COULD do something similar for merging such that `ports: []` overrides and "clears".

**Comment by milas** [comment]
I wonder if during merging we need to have the original project in `map[string]interface{}` format handy and a helper like `isFieldDefined("services.foo.ports")` so we can only consider explicitly set fields.

**Comment by ndeloof** [comment]
also see https://github.com/docker/compose/issues/8699

**Comment by ndeloof** [comment]
This indeed will require compose-go to distinguish a field being set to default value _vs_ an explicit `null` assignment. We could manage this before yaml model is mapped to go structs, as a `map[string]interface{}` tree.
Anyway, proposal here is more to collect feedback on syntax and document this behavior
