### ISSUE TITLE
'include' documentation should specify applicable version

### ISSUE THREAD

**Issue by kchawla-pi** [compose-spec/compose-spec#395]
File: [14-include.md](https://docs.docker.com/compose/compose-file/14-include/)

Documentation for 'include' in compose file should specify which version of compose file will support this. I wasted hours trying to get it to work with my file (v 3.8) & docker installation (Docker Desktop for Windows v4.20.1)

**Comment by glours** [comment]
@kchawla-pi the `version` attribute has been deprecated with the introduction of the Compose specification. `Include` should support any compose file which respect the Compose specification

**Comment by kchawla-pi** [comment]
Docker version then?

Because I get `(root) Additional property include is not allowed`.

**Comment by jdreesen** [comment]
It's supported in [Docker Compose v2.20](https://github.com/docker/compose/releases/tag/v2.20.0). Docker Desktop is still on `v2.19`.

**Comment by glours** [comment]
@kchawla-pi ok I understand your trouble now. 
So I checked the Docker Compose page about [include](https://docs.docker.com/compose/multiple-compose-files/include/) and the version needed is the first thing mentioned. 
This repository concerns the definition of the specification, so it should not be coupled to a specific implementation, that's why you won't see any reference to a particular version of product here.
