### ISSUE TITLE
docker-compose .env file support dynamic values

### ISSUE THREAD

**Issue by yamatoRT** [compose-spec/compose-spec#94]
**What is the problem you're trying to solve**
The main problem is use UID and GID variables in docker-compose.
```yml
# docker-custom.yml
web:
  # Set your user and group id.
  # View your user id with command 'id -u' and your group id with 'id -g'.
  user: "${UID}:${GID}"
```
this doesn't work because, UID and GID are not environment variable. There are shell variable. you need to do a export of custom environment variable before.

**Describe the solution you'd like**
In docker-compose repository, for implement it I offer to the possibility to import the environment variable with bash interpreter, if you add :bash after the env file path.
```yml
web:
  user: "${CUSTOM_UUID}:${CUSTOM_GUID}"
  env_file:
    tests/fixtures/env/get_uuid.env:bash
```
with `tests/fixtures/env/get_uuid.env env` file :
```bash
CUSTOM_UUID=$(id -u)
CUSTOM_GUID=$(id -g)
```
but i need your approval for the new syntax.

**Additional context**
The issues in docker-compose repository :
  - https://github.com/docker/compose/issues/3849
  - https://github.com/docker/compose/issues/2380

The pull request in docker-compose repository : 
  - https://github.com/docker/compose/pull/7598

**Comment by EricHripko** [comment]
Let's take a step back: based on the discussions linked, this request appears to be linked to containers creating files with unexpected/inappropriate permissions on the host (via mounts). We should possibly first explore if it's something that should be addressed in the spec or if it's up to the container technology to handle (e.g., Docker for Mac/Windows Hyper-V remaps permissions for files and there's also [userns-remap](https://docs.docker.com/engine/security/userns-remap/) and `setfacl`).

If it is indeed something to be addressed in the spec, then it seems the core problem we're trying to solve is making sure that UID/GID inside the container matches the host one. This, however, reveals a bunch of gotchas like:
- How should such Compose files behave on a system that doesn't have a concept of uid/gid? (e.g., Windows)
- Does expected software work inside containers without `useradd` for the requested uid/gid?
- Would it make sense to make `$UID`/`$GID` into special substitution variables in Compose spec instead of allowing subshells? 

On a more general note, enabling subshells inside a declarative language seems dangerous and potentially hurts portability. Some concerns would include:
- What if subshell contains a malicious command (e.g., `rm -rf ~`)?
- What if subshell contains a non-repeatable command? `compose up` would succeed, but you would lose access to you services afterwards;
- How do we select the interpreter (in case there's multiple `bash` installs) and what if desired interpreter isn't available on the host?
- What happens on Mac and Windows where some (or most) of these commands won't work?

**Comment by yamatoRT** [comment]
Hello,

I think you have reason, use subshell it's not the good way. I close this issue.

Thanks for your instructive answer.
