### ISSUE TITLE
Proposal: profiles

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-spec#97]
**What is the problem you're trying to solve**
Many users define in a compose file some additional container that they use during development as "one-off" tasks using `docker-compose run` command, but are not part of their compose application. As one can't disable a service in a compose file, they have to maintain a separated compose file, and then use explicit `--file` option.

It's also a common practice to have separated override compose file to address different environments, typically to configure some services with debug port exposed during development.

This proposal is about making those usage patterns more canonical by providing the adequate descriptive apporach to select a sub/superset of containers in a compose file, and apply some override files.

**Describe the solution you'd like**
Compose specification introduce a new concept as *profile* that a Compose implemenation can use to select the services to be ran when loading a Compose model.

1. Introduce a new `profiles` attribute at services level as a string list. If not set, it will default to `profiles: ["default"]`. In regards to https://github.com/compose-spec/compose-spec/issues/87 this is equivalent to `auto_up: true`

Compose implementations whith profile support MUST ignore services which have a profile attribute but don't match the current profile. Services without a profile attribute always match.

Selecting active profile(s) can be implemented by any mechanism, typically flags or environment variable `DOCKER_COMPOSE_PROFILE`, but this is an implementation detail not to be defined y the spec.

Running `compose up` with "debug" profile enabled will run: 
- services with no `profiles` attribute
- services which `profiles` list includes "debug" in the `profiles` attribute. 

2. Clarify by the specification the selection of an override compose file to be merged with the main one. With profile support, a Compose implementation will check for the presence of a `compose-[profile].yaml` file aside the main compose file, and automatically merge it with the main model. Adopting this pattern by the spec would actually make a common practice a canonical one - docker-compose already does this by loading a `docker-compose-overrides.yaml` file if present.

**Additional context**
This proposal is a follow-up for https://github.com/docker/compose/issues/7539#issuecomment-645361324 and address https://github.com/compose-spec/compose-spec/issues/87

**Comment by rumpl** [comment]
I'm making a connection with Spring profiles, do we want to accept multiple profiles when running an application, eg. `compose run --profile debug --profile elk` for example?

**Comment by rumpl** [comment]
If I understand correctly, if I run 

```
compose --profile test up
```
it will load and merge the `docker-compose-test.yaml` file. But if I run 

```
compose --profile default up
```
then it will load the `docker-compose-overrides.yaml` one, right?

If this is the case then we would need to make this very clear in the spec/documentation and maybe event while running the app.

**Comment by ndeloof** [comment]
> do we want to accept multiple profiles

It makes perfect sense imho.

> it will load the docker-compose-overrides.yaml one, right?

This proposal doesn't cover the usage of `docker-compose-overrides.yaml`, which is not (yet?) covered by the spec and is a docker-compose specific implemenation detail. This is actually the first time in the spec we consider the Compose model can be provided by a set of yaml files, and not a single source.

imho we should clarify this and make `docker-compose-overrides.yaml` a canonical "local overrides" file to be always applied to the Compose model. Profiles are then another mechanism to select some additional overrides to be merged.

i.e 
```
compose --profile test up
```
will load and merge `compose.yaml`, `compose-test.yaml` and `compose-overrides.yaml` files. 
```
compose --profile default up
```
will load and merge `compose.yaml` and `compose-overrides.yaml` f

**Comment by rumpl** [comment]
> imho we should clarify this and make `docker-compose-overrides.yaml` a canonical "local overrides" file to be always applied to the Compose model. Profiles are then another mechanism to select some additional overrides to be merged.

Sounds about right, there's just the `compose --profile overrides up` case to define.

**Comment by acran** [comment]
> If not set, it will default to profiles: ["default"].
> [...]
> Services without a profile attribute always match.

This somehow is contradicting: if `profiles` defaults to `["default"]` services without specified `profiles` would start _only_ for `default`. To bring this in harmony with the second statement the default should be something like `profiles: ["*"]` (pseudo-syntax).

But maybe defaulting to `profiles: ["default"]` could be better anyway? For example having a profile `frontend_only`:
* with default `profiles: ["default"]` you only have to add `profiles: ["default", "frontend_only"]` to the frontend services
* with default `profiles: ["*"]` you _additionally_ have to add `profiles: ["default"]` to _all other_ services

Also the implementation could be more straight forward in the former case since there is no special handling besides the default value when unspecified.


Another question to clarify is: how should `profiles` be merge with overrides?
Looking at the [current behavior for other multi-value options](https://docs.docker.com/compose/extends/#adding-and-overriding-configuration) override values should be added to base values. On the other hand it might useful to be able to remove a service from a profile with an override?

**Comment by acran** [comment]
> Compose implementations whith profile support MUST ignore services which have a profile attribute but don't match the current profile.

To clarify: what does this imply for services not matching the current profile but pulled in by `depends_on` from another service that is?
Would this result in an error because the dependency could "not be found" or would it be started anyway?

**Comment by ndeloof** [comment]
`profiles: ["*"]` is indeed a better way to express what I had in mind :)

**Comment by ndeloof** [comment]
> what does this imply for services not matching the current profile but pulled in by depends_on from another service that is?

I'd prefer we don't include too much magic and consider profiles as a "filter" applied on yaml file to include/exclude services, so that a missing reference is considered an error, and not an "implicit profile". But this could be debated if other feel like this could be usefull

**Comment by EricHripko** [comment]
Agree with @ndeloof - it'd make sense for profiles to return an error if a dependency (`depends_on`, `service:` mode for ipc/pid/network etc) isn't included explicitly. This also serves for a more consistent UX since this is already how `extends:` field is declared in the spec.

**Comment by acran** [comment]
Playing around with the `profiles` concept and its edge cases in my head I have some more thoughts on this. But small disclaimer here: coming from the desire to just disable some services from being started _by default_ (#87) I may be a bit biased towards some use cases here.

### coupling profiles with override yaml files
Currently this proposal does two things:
1. introduce the `profiles` attribute to services
2. add rules to automatically include additional overrides for profiles

But I don't feel like 2. is actually necessary to solve to problem we're addressing here:
the main reason why users _currently_ use multiple yml files (in this scenario) is because there is no other way to specify services but don't let them be started automatically. The introduction of the `profiles` attribute (1.) solves this now and allows to just specify all services and one-off tasks in a single `compose.yml` and select them with the `--profile` flag, eliminating the need for multiple `compose.yml` files.

> It's also a common practice to have separated override compose file to address different environments, typically to configure some services with debug port exposed during development.

This I see as a separate thing because it is about _environment-specific_ changes. For these there already is an established solution: _environment variables_ and the `.env` file where one could e.g. specify `COMPOSE_FILE`.

In my opinion **not** mixing `profiles` and environments but keeping them independent would offer the most flexibility to the user  and therefore this part should be dropped from the proposal - especially since this requires to first add overrides to the spec.

But if this will be included I would propose a naming convention of `compose-overrides.[profile].yml` to emphasize that it is used to override/extend already defined services with profile-specific stuff. This would also avoid this edge case:
> there's just the compose --profile overrides up case to define.

### default value `profiles: ["*"]` vs `profiles: ["default"]`
I'm still a bit undecided on this one: I find
> --profile _profile-name_    start services that have _profile-name_ listed in their `profiles` **only**. If not specified, `profiles` defaults to `["default"]`

much more intuitive - and probably also easier to implement since there is no special handling of unspecified values other than the default value - than
> --profile _profile-name_    start services that have _profile-name_ listed in their `profiles` or have no `profiles` specified

Take for example a `compose.yml` with 14 services. The user now wants to define and start a profile "dev" with **only** 3 of the services:
With a `profiles: ["default"]` default value the user only needs to add `profiles` to those 3 services:
~~~sh
docker-compose up --profile dev # start only the 3 dev services

# start dev services _and_ default services
docker-compose up --profile dev --profile default
~~~

With a `profiles: ["*"]` default on the other hand the user has to explicitly specify `profiles: ["default"]` to **all** other of the 14 services (and possibly in all override files) to achieve the same.

One could of course argue in such a case it is easier to split those 3 services into their own `compose.yml`. But with dependencies to other services/sharing with other profiles this may lead to duplication or back to the mess with needing to include multiple `compose.yml` we wanted to avoid with this proposal.

### `--profile` as filter
>>what does this imply for services not matching the current profile but pulled in by depends_on from another service that is?
>
> I'd prefer we don't include too much magic and consider profiles as a "filter" applied on yaml file to include/exclude services, so that a missing reference is considered an error, and not an "implicit profile".

> it'd make sense for profiles to return an error if a dependency (depends_on, service: mode for ipc/pid/network etc) isn't included explicitly

I'd agree on this but I found some problems with it:
One of the most requested use cases for this feature is to be able to specify "one-off" tasks or services which are not started by `docker-compose up` but only explicitly - see discussion in docker/compose#1896 and the [opening post](https://github.com/compose-spec/compose-spec/issues/97#issue-685257604)
> Many users define in a compose file some additional container that they use during development as "one-off" tasks using `docker-compose run` command, but are not part of their compose application.

For this consider the following (abbreviated) `compose.yml`:
~~~yml
services:
  database:
    profiles: ["default"]
    # ...
  migrations:
    profiles: ["run-never"]
    depends_on: ["database"]
~~~

(in reference to [comment on docker/compose#7539](https://github.com/docker/compose/issues/7539#issuecomment-645366728))

`docker-compose up` will only start the default services, i.e. `database`. The `migrations` service/task is intended to be only started explicitly. But what happens when you run `docker-compose up migrations` or `docker-compose run migrations`?
* will it start `migrations` and `database` as its dependency?
* will it error out since `migrations` is not in the `default` profile?

The latter one means that one must specify the correct profile: `docker-compose up --profile run-never migrations`
But then this would error out because the `database` dependency is not in the `run-never` profile and one must use `docker-compose up --profile run-never --profile default migrations`

This not only is much more to type but also requires the user to remember/look up which profile(s) the desired service/task and all its transitive dependencies belong to - which is exactly what users want to avoid see docker/compose#1896.


Instead of a "filter" over the available services I would understand `profiles` more of a definition of the _default services_ which should be started when no services are _explicitly_ given including their dependencies. Therefore I also see the `--profile` flag as a flag to the `up` subcommand (and `create`) and not the `docker-compose` main command.

In this interpretation `profiles` may be not the best term for this. Maybe something like `target` would be a better name?

**Comment by ndeloof** [comment]
Proposal indeed covers two approaches: 
- a way to make some elements optional, only being included in the compose model when profile is active
- a canonical approach to multiple compose file being merged, with typical target to cover distinct environments

Both are complimentary imho. environment variables allow to tweak a compose file with distinct values, but not to apply significant changes. compose file overrides allow to redefine a volume, for sample to use cloud platform specific driver_options while for local development you will just use plain docker volumes.

profile default value to be `*` is my intent to express that component which don't have a profile set will ALWAYS be enabled in the compose model. Such components are the backbone of your application, and there's no reason to exclude them. In your sample of a compose file with 14 services, and user who wants to run only 3 of them, I hardly can imagine why this compose file has 14 services, which should not be declared as specific to a profile to cover an explicit use-case. A compose file should be use to define an application model, not just as a generic bag to define random stuff and cherry-pick the one you'd like to run.

About one-off tasks, your sample uses an explicit service being passed as parameter. In such circumstances we can clarify that such an explicit service reference do enable this service, whenever it has been disabled for inactive profile. And here again, `database` been part of the application core does not require a profile set and will always be enabled.

**Comment by EricHripko** [comment]
Agreed on above - while environment variables and `.env` files go a long way, having a separate profile-specific file gives user full control over tweaking attributes of the service. I like @acran suggestion of `compose-overrides.[profile].yml` - it seems like a logical extension to existing override mechanism and an elegant solution to avoid special behaviour around `--profile overrides`.

Correct me if I'm wrong, but It seems like this proposal suggests that `*` (or `default` since it seems like the difference is just naming) profile is for services that are always on. This means that the suggested Compose file could look like:
```yml
services:
  database:
    # ...
  migrations:
    profiles: ["one-off"]
    depends_on: ["database"]
```
With the CLI invocation looking something like `compose --profile one-off run --rm migrations`. This would the pull in:
 - `migrations` service since it matches the active `one-off` profile
- `database` service since it matches always-on `*` profile

I think the last point raised by @acran can be potentially seen as optimisation in the tooling. Maybe CLI tools could pick up the profiles of the specified service if no `--profile` is present? This, however, could also introduce unexpected complexity since (from what I understand) Compose CLIs rely on all input `.yaml`s parsed and combined from the get-go.

**Comment by acran** [comment]
> environment variables allow to tweak a compose file with distinct values, but not to apply significant changes. compose file overrides allow to redefine a volume

Using `COMPOSE_FILE` environment variables already allow to pull in additional overrides and so also apply significant changes.

> In your sample of a compose file with 14 services, and user who wants to run only 3 of them, I hardly can imagine why this compose file has 14 services, which should not be declared as specific to a profile to cover an explicit use-case.

Because the user _wants_ to - which doesn't necessarily mean the compose model has to support this use case. So this example was made to visualize the "problems" in such edge cases to be better able to decide if that uses cases should be supported anyway.

> A compose file should be use to define an application model, not just as a generic bag to define random stuff and cherry-pick the one you'd like to run.

I didn't consider it that way, but agreed.

> Proposal indeed covers two approaches:

Coming from #87 for me the first approach would be enough and no need for the second. But as long as this proposal covers the first one I'm happy with both :smile: 

> About one-off tasks, your sample uses an explicit service being passed as parameter. In such circumstances we can clarify that such an explicit service reference do enable this service, whenever it has been disabled for inactive profile. 

Looking at the most requested use cases in docker/compose#1896 this is a **very** important clarification that should be included here so these use cases can be supported.

> Correct me if I'm wrong, but It seems like this proposal suggests that * (or default since it seems like the difference is just naming) profile is for services that are always on. This means that the suggested Compose file could look like:

Not really: the database is explicitly assigned to the `default` profile - **only**. To better clarify the point replace `default` with any other profile e.g. `backend`. Starting the `migrations` service would then require this command:
~~~sh
compose --profile one-off --profile backend run --rm migrations
~~~

But the desired command line should be just
~~~sh
compose run --rm migrations
~~~
because having to type out everything explicitly and having to memorize/lookup the correct profile(s) for all services and dependencies makes it very inconvenient.

Therefore I would like to extend to 
> In such circumstances we can clarify that such an explicit service reference do enable this service **and its dependencies**, whenever it has been disabled for inactive profile.

But this would be great to also cover and resolve the use case of #87.

**Comment by ndeloof** [comment]
if `database` has no profile set it will be active whatever profile you select.
Then running `compose run --rm migrations` _could_ enable "migrations" even it has an inactive profile assigned as service is **explicitly** selected by command. Otherwise it would be disabled until profile is enabled.

So
- `compose run --rm migrations` will run `migrations` and it's dependent service `database`
- `compose up --profile one-off` will also run `migrations` and `database`
- `compose up` will only run `database` 

Hope this makes my proposal clearer :)

**Comment by acran** [comment]
> Hope this makes my proposal clearer :)

Yes, this is exactly how I understood it.

But my example was aiming into the other direction: what if the service depended on is not in the default/_always-enabled_ profile _by purpose_?

So maybe a new example to make it clearer:
~~~yml
services:
  frontend:
    # this is our core service/the actually application
  mock_backend:
    # a dummy backend used for testing in local development
    profiles: ["dev"]
    depends_on: ["database"]
  database:
    # database for mock_backend
    profiles: ["dev"]
  phpmyadmin:
    # user-friendly frontend to inspect and manipulate the database
    profiles: ["run-never"]
    depends_on: ["database"]
~~~

Here the `phpmyadmin` service is intended to only ever be started manually. But starting it with
~~~sh
compose up phpmyadmin
~~~
would fail because its dependency `database` is not in the default/_always-enabled_ profile and therefore can not be satisfied.

One could argue here that it is the configuration author's responsibility to assign dependent services common profiles and so far I could agree with that. But this still wouldn't work in the following case:
~~~sh
compose up mock_backend
~~~
Although `mock_backend` and `database` are in the same profiles this would fail because `database` was not _explicitly_ provided according to the [current proposed spec change](https://github.com/compose-spec/compose-spec/pull/98/files#diff-958e7270f96f5407d7d980f500805b1bR181-R182):
> References to other services (by `links`, `extends` or shared resource syntax `service:xxx`) **MUST not** automatically enable a component that would otherwise have been ignored by active profiles.

The only ways to start the service would be:
~~~sh
compose up --profile dev mock_backend
compose up mock_backend database
~~~

Which again would require the user to know or lookup the correct profile for the requested service _and all its dependencies_ or explicitly provide all (transitive) dependencies. Since this "little" inconvenience was the major pain point in the discussions at docker/compose#1896 I propose this change
> References to other services (by `links`, `extends` or shared resource syntax `service:xxx`) **MUST** automatically enable a component that would otherwise have been ignored by active profiles.

Or as a compromise only the profiles of the explicitly enabled services should be activated as well, [as suggested](https://github.com/compose-spec/compose-spec/issues/97#issuecomment-683398226) by @EricHripko:
> References to other services (by `links`, `extends` or shared resource syntax `service:xxx`) MUST not automatically enable a component that would otherwise have been ignored by active profiles **unless they share a profile with a component explicitly targeted by a command**.

For a reasonably good written compose file this would effectively be equivalent to the former and provide a sufficient and intuitive convenience for the users.

**Comment by ndeloof** [comment]
> `compose up phpmyadmin` would fail because its dependency database is not in the default/always-enabled profile and therefore can not be satisfied.

indeed, and I believe this is sane behaviour. As `database` is guarded by `dev` profile it should not be magically enabled.

> require the user to know or lookup the correct profile

exact. Profiles should be defined by usage, and not just assing random profiles. If `mock_backend` depends on `database` that has been declared in `dev` profile, then this whole thing takes place in a development usage, and probably user will have `DOCKER_COMPOSE_PROFILE=dev` set
(I also had in mind this might be something we could set by docker context)

> unless they share a profile with a component explicitly targeted by a command.

That's an option indeed, but for such use case I believe we should promote use of distinct composefile per usage, so that users maintain a `compose-dev.yaml` file to include such mocks and dependent services as long as they aren't relevant otherwise.

**Comment by acran** [comment]
> That's an option indeed, but for such use case I believe we should promote use of distinct composefile per usage, so that users maintain a `compose-dev.yaml` file to include such mocks and dependent services as long as they aren't relevant otherwise.

This is actually what `docker-compose` currently _does_ promote - because there is no other way to achieve something like this at the moment - see solution 1. in the opening post of docker/compose#1896.
But as the very long discussion and continued requests for such a feature 5 years later clearly show: this is not an adequate solution for many users, and the reason why I opened #87. Because having to know and type out:
~~~sh
compose -f compose-de.yaml up mock_backend
# or
compose up --profile dev mock_backend
~~~
is not much of a difference convenience-wise.

Having `DOCKER_COMPOSE_PROFILE=dev` set in the environment would mean that the `mock_backend` would be started **by default** in that environment and not **only on-demand**. And it would not be a huge difference to `COMPOSE_FILE=compose.yml:compose-dev.yml`

**Comment by ndeloof** [comment]
> this would be a bit inconsistent 

Right, maybe this is not such a good idea to magically enable a service when explicitly invoked by name.

>  mock_backend would be started by default

only if you use `up` command, and not `run` to just run a single service (and dependencies)

**Comment by acran** [comment]
> only if you use `up` command, and not `run` to just run a single service (and dependencies)

Yes. Which means wanting to start the core services (in this example `frontend`) by just doing
~~~sh
docker-compose up
~~~
would - in this environment - also start `mock_backend` and `database` which is undesired since these are intended to be started only _on-demand_. This becomes a bit clearer when thinking of a "one-off service" or "task" which has dependencies that are only in the same profile(s).

**Comment by acran** [comment]
> Right, maybe this is not such a good idea to magically enable a service when explicitly invoked by name.

Also correct: _conceptually_ this is actually wrong and has some hidden magic in it. But the reason for this is the convenience it provides the users and which makes sense from a UX perspective since it makes `docker-compose` a really useful tool which does not get in the way of the users^^
